{
 "title": "DEMO - Hardware",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Data_Source", "label": "Data Source", "query": "influxdb" },
   { "name": "Gateway", "label": "fitlet2", "query": "SHOW MEASUREMENTS" },
   { "name": "Gateway2", "label": "GW", "query": "SHOW MEASUREMENTS" },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"[[Gateway]]\" WITH KEY =\"sensor_mac\""
   }
  ]
 },
 "panels": [
  { "title": "Number of sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fitlet2",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "select count(distinct(\"sensor_mac\")) from (SELECT count(\"sensor_rssi\")  / 2.4 FROM /^$Gateway$/ WHERE $timeFilter GROUP BY time(1m), \"sensor_mac\" fill(0))",
     "select": [
      [
       { "params": [ "sensor_battery" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "GW",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "select count(distinct(\"sensor_mac\")) from (SELECT count(\"sensor_rssi\")  / 2.4 FROM /^$Gateway2$/ WHERE $timeFilter GROUP BY time(1m), \"sensor_mac\" fill(0))",
     "select": [
      [
       { "params": [ "sensor_battery" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "fitlet2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "select mean(\"count\") from (SELECT count(\"sensor_rssi\") * last(\"sensor_adv\") /20 as \"count\" FROM /^$Gateway$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(2s), \"sensor_mac\" fill(none))\n",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "fitlet2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "format": "pps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT count(\"sensor_value\")/2 as \"count\" FROM /^$Gateway$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(2s) fill(none)\n",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "GW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "select mean(\"count\") from (SELECT count(\"sensor_rssi\") * last(\"sensor_adv\") /20 as \"count\"  FROM /^$Gateway2$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(2s), \"sensor_mac\" fill(none))\n",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "GW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "format": "pps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT count(\"sensor_value\")/2 as \"count\" FROM /^$Gateway2$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(2s) fill(none)",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "fitlet2 - Packets per second received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT count(\"sensor_value\") * last(\"sensor_adv\") /10 AS \"Per second\" FROM \"autogen\"./^$Gateway$/ WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND $timeFilter GROUP BY time(1s), \"sensor_mac\" fill(null)",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Per second" ], "type": "alias" }
      ],
      [
       { "params": [ "sensor_adv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "GW - Packets per second received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway2$/",
     "query": "SELECT count(\"sensor_value\") * last(\"sensor_adv\") /10  AS \"Per second\" FROM \"autogen\"./^$Gateway2$/ WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND $timeFilter GROUP BY time(1s), \"sensor_mac\" fill(0)",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Per second" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  { "title": "Sensors Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "fitlet2",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" }
     ],
     "measurement": "/^$Gateway$/",
     "select": [
      [
       { "params": [ "sensor_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "RSSI" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GW",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" }
     ],
     "measurement": "/^$Gateway2$/",
     "select": [
      [
       { "params": [ "sensor_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "RSSI" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fitlet2 - Available Sensors",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor_type" ], "type": "tag" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT last(\"sensor_rssi\") AS \"RSSI\", last(\"sensor_battery\") AS \"BATTERY\" FROM \"autogen\"./^$Gateway$/ WHERE $timeFilter GROUP BY \"sensor_type\", \"sensor_mac\" fill(null)",
     "select": [
      [
       { "params": [ "sensor_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RSSI" ], "type": "alias" }
      ],
      [
       { "params": [ "sensor_battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "BATTERY" ], "type": "alias" }
      ],
      [
       { "params": [ "sensor_adv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ADV" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GW - Available Sensors",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor_type" ], "type": "tag" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway2$/",
     "query": "SELECT last(\"sensor_rssi\") AS \"RSSI\", last(\"sensor_battery\") AS \"BATTERY\" FROM \"autogen\"./^$Gateway2$/ WHERE $timeFilter GROUP BY \"sensor_type\", \"sensor_mac\" fill(null)",
     "select": [
      [
       { "params": [ "sensor_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RSSI" ], "type": "alias" }
      ],
      [
       { "params": [ "sensor_battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "BATTERY" ], "type": "alias" }
      ],
      [
       { "params": [ "sensor_adv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ADV" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Measurments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "fitlet2 - Sensor Values",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "GW - Sensor Values",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway2$/",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  }
 ]
}