{
 "title": "DEMO - Alerting",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Data_Source_Cloud", "label": "Cloud", "query": "influxdb" },
   { "name": "Data_Source_Local", "label": "Device Local", "query": "influxdb" },
   { "name": "Chorongraf_Cloud", "label": "Cloud Chronograf", "query": "influxdb" },
   { "name": "Chorongraf_Local", "label": "Local Chronograf", "query": "influxdb" },
   { "name": "Gateway", "label": "Gateway", "query": "SHOW MEASUREMENTS" },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"[[Gateway]]\" WITH KEY =\"sensor_mac\""
   }
  ]
 },
 "panels": [
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT count(\"sensor_value\") * last(\"sensor_adv\") /10 AS \"Per second\" FROM \"autogen\"./^$Gateway$/ WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND $timeFilter GROUP BY time(1s), \"sensor_mac\" fill(null)",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Per second" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "measurement": "alerts",
     "query": "SELECT \"value\" as \"Alert Value\" FROM \"alerts\"  WHERE (\"alertID\" = 'Packets Lost') AND (\"level\"='CRITICAL' ) LIMIT 20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "alertName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "CRITICAL" }
     ]
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "query": "SELECT count(\"sensor_value\") * last(\"sensor_adv\") /10 AS \"Per second\" FROM \"autogen\"./^$Gateway$/ WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND $timeFilter GROUP BY time(1s), \"sensor_mac\" fill(0)",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Per second" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "measurement": "alerts",
     "query": "SELECT \"value\" as \"Alert Value\" FROM \"alerts\"  WHERE (\"alertID\" = 'Packets Lost') AND (\"level\"='CRITICAL' ) LIMIT 20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "alertName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "CRITICAL" }
     ]
    }
   ]
  },
  { "title": "Measurments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "measurement": "alerts",
     "query": "SELECT \"value\" as \"Alert Value\", \"sensor_unit\" as \"Unit\", \"sensor_mac\" as \"MAC\" FROM \"alerts\"  WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND (\"alertID\" = 'Threshold') AND (\"level\"='CRITICAL' ) LIMIT 20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "alertName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "CRITICAL" }
     ]
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor_mac",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor_mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Gateway$/",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "targets": [
    {
     "measurement": "alerts",
     "query": "SELECT \"value\" as \"Alert Value\", \"sensor_unit\" as \"Unit\", \"sensor_mac\" as \"MAC\" FROM \"alerts\"  WHERE (\"sensor_mac\" =~ /^$Sensor$/) AND (\"alertID\" = 'Threshold') AND (\"level\"='CRITICAL' ) LIMIT 20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "alertName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "CRITICAL" }
     ]
    }
   ]
  }
 ]
}