{
 "title": "DEMO - Software",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Data_Source_Cloud", "label": "Cloud", "query": "influxdb" },
   { "name": "Data_Source_Local", "label": "Device Local", "query": "influxdb" },
   { "name": "Gateway", "label": "Gateway", "query": "SHOW MEASUREMENTS" },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"[[Gateway]]\" WITH KEY =\"sensor_mac\""
   },
   {
    "name": "Alerting_Sensor",
    "label": "Alerting for",
    "query": "SHOW TAG VALUES FROM \"[[Gateway]]\" WITH KEY =\"sensor_mac\""
   }
  ]
 },
 "panels": [
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Measurments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Alerting_Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Measurments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Alerting_Sensor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Number of sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "select count(distinct(\"sensor_mac\")) from (SELECT count(\"sensor_rssi\")  / 2.4 FROM /^$Gateway$/ WHERE $timeFilter GROUP BY time(1m), \"sensor_mac\" fill(0))",
       "select": [
        [
         { "params": [ "sensor_battery" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "select count(distinct(\"sensor_mac\")) from (SELECT count(\"sensor_rssi\")  / 2.4 FROM /^$Gateway$/ WHERE $timeFilter GROUP BY time(1m), \"sensor_mac\" fill(0))",
       "select": [
        [
         { "params": [ "sensor_battery" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "select mean(\"count\") from (SELECT count(\"sensor_rssi\")  / 0.04 FROM /^$Gateway$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(1s), \"sensor_mac\" fill(none))\n",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "select mean(\"count\") from (SELECT count(\"sensor_rssi\")  / 0.04 FROM /^$Gateway$/ WHERE $timeFilter and (\"sensor_mac\" =~ /^$Sensor$/) GROUP BY time(1s), \"sensor_mac\" fill(none))\n",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor_mac",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Per second" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor_mac",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Per second" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Sensors Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device",
     "type": "snuids-radar-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "RSSI" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "snuids-radar-panel",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "RSSI" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Device",
     "type": "table",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "sensor_type" ], "type": "tag" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "SELECT last(\"sensor_rssi\") AS \"RSSI\", last(\"sensor_battery\") AS \"BATTERY\" FROM \"autogen\"./^$Gateway$/ WHERE $timeFilter GROUP BY \"sensor_type\", \"sensor_mac\" fill(null)",
       "select": [
        [
         { "params": [ "sensor_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RSSI" ], "type": "alias" }
        ],
        [
         { "params": [ "sensor_battery" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "BATTERY" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "table",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "sensor_type" ], "type": "tag" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "query": "SELECT last(\"sensor_rssi\") AS \"RSSI\", last(\"sensor_battery\") AS \"BATTERY\" FROM \"autogen\"./^$Gateway2$/ WHERE $timeFilter GROUP BY \"sensor_type\", \"sensor_mac\" fill(null)",
       "select": [
        [
         { "params": [ "sensor_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RSSI" ], "type": "alias" }
        ],
        [
         { "params": [ "sensor_battery" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "BATTERY" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Measurments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor_mac",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    },
    {
     "title": "Cloud",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor_mac",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "sensor_mac" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Gateway$/",
       "select": [
        [
         { "params": [ "sensor_value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor_mac", "operator": "=~", "value": "/^$Sensor$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}